-- Tarefa 3.a: Script de criação da tabela dbo.SindromeGripal.

USE OpenDataSUS;
GO

CREATE TABLE [dbo].[SindromeGripal]
(
    [id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [sintomas] VARCHAR(200) NULL,
    [profissionalSaude] VARCHAR(10) NULL,
    [racaCor] VARCHAR(10) NULL,
    [outrosSintomas] VARCHAR(500) NULL,
    [outrasCondicoes] VARCHAR(300) NULL,
    [profissionalSeguranca] VARCHAR(10) NULL,
    [cbo] VARCHAR(200) NULL,
    [condicoes] VARCHAR(300) NULL,
    [sexo] VARCHAR(15) NULL,
    [estado] VARCHAR(30) NULL,
    [estadoIBGE] VARCHAR(2) NULL,
    [municipio] VARCHAR(100) NULL,
    [municipioIBGE] VARCHAR(7) NULL,
    [origem] VARCHAR(30) NULL,
    [estadoNotificacao] VARCHAR(30) NULL,
    [municipioNotificacao] VARCHAR(100) NULL,
    [municipioNotificacaoIBGE] VARCHAR(7) NULL,
    [evolucaoCaso] VARCHAR(30) NULL,
    [classificacaoFinal] VARCHAR(50) NULL,
    [codigoEstrategiaCovid] VARCHAR(2) NULL,
    [codigoBuscaAtivaAssintomatico] VARCHAR(2) NULL,
    [outroBuscaAtivaAssintomatico] VARCHAR(150) NULL,
    [codigoTriagemPopulacaoEspecifica] VARCHAR(2) NULL,
    [outroTriagemPopulacaoEspecifica] VARCHAR(150) NULL,
    [codigoLocalRealizacaoTestagem] VARCHAR(2) NULL,
    [outroLocalRealizacaoTestagem] VARCHAR(150) NULL,
    [codigoRecebeuVacina] VARCHAR(2) NULL,
    [codigoLaboratorioPrimeiraDose] VARCHAR(100) NULL,
    [codigoLaboratorioSegundaDose] VARCHAR(100) NULL,
    [lotePrimeiraDose] VARCHAR(30) NULL,
    [loteSegundaDose] VARCHAR(30) NULL,
    [codigoContemComunidadeTradicional] VARCHAR(2) NULL,
    [source_id] VARCHAR(20) NULL,
    [excluido] BIT NULL,
    [validado] BIT NULL,
    [codigoDosesVacina] VARCHAR(10) NULL,
    [estadoNotificacaoIBGE] VARCHAR(2) NULL,
    [totalTestesRealizados] INT NULL,
    [dataNotificacao] DATE NULL,
    [dataInicioSintomas] DATE NULL,
    [dataEncerramento] DATE NULL,
    [dataPrimeiraDose] DATE NULL,
    [dataSegundaDose] DATE NULL,
    [codigoEstadoTeste1] VARCHAR(2) NULL,
    [codigoTipoTeste1] VARCHAR(2) NULL,
    [codigoFabricanteTeste1] VARCHAR(5) NULL,
    [codigoResultadoTeste1] VARCHAR(2) NULL,
    [codigoEstadoTeste2] VARCHAR(2) NULL,
    [codigoTipoTeste2] VARCHAR(2) NULL,
    [codigoFabricanteTeste2] VARCHAR(5) NULL,
    [codigoResultadoTeste2] VARCHAR(2) NULL,
    [codigoEstadoTeste3] VARCHAR(2) NULL,
    [codigoTipoTeste3] VARCHAR(2) NULL,
    [codigoFabricanteTeste3] VARCHAR(5) NULL,
    [codigoResultadoTeste3] VARCHAR(2) NULL,
    [codigoEstadoTeste4] VARCHAR(2) NULL,
    [codigoTipoTeste4] VARCHAR(2) NULL,
    [codigoFabricanteTeste4] VARCHAR(5) NULL,
    [codigoResultadoTeste4] VARCHAR(2) NULL,
    [dataColetaTeste1] DATE NULL,
    [dataColetaTeste2] DATE NULL,
    [dataColetaTeste3] DATE NULL,
    [dataColetaTeste4] DATE NULL,
    [idade] INT NULL,
    [NomeArquivoOrigem] VARCHAR(260) NULL,
    [DataHoraCarga] DATETIME NOT NULL DEFAULT (GETDATE())
);
GO